### PR TITLE
Verification Dsound 4039, 4134 Database

### PR DESCRIPTION
**Pull request by jarupxx**
Added Dsound 4039, 4134 OOVPA that verification needed.

Verified with
- [4039] Azurik PAL
- [4134] Double-S.T.E.A.L
- [4242] NFL Blitz 2002

### CODE REVIEW

**Comment by RadWolfie** [comment]
Looks good. However, I believe CDirectSoundBuffer_xxxxx you created needs offset 0x00's value. For real example at offset 0x06: `cmp dword ptr [_pCriticalSection_],0`

0x06 | 0x07 | 0x08 | 0x09 | 0x0A | 0x0B | 0x0C
--- | --- | --- | --- | --- | --- | ---
0x83 | 0x3D | 0x6C | 0xBC | 0x22 | _**0x00**_ | _**0x00**_

Between 4039 and 4134 revision, most of them calling to DirectSoundEnterCriticalSection, are forward by one offset. If we do stop at ~~first~~ last find, then it will use ~~4039~~ 4134 instead of ~~4134~~ 4039. Locking offset 0x00 or 0x06 down to prevent wrong "start point" of function will help a lot better. Usually I just use offset 0x00 since 90% of the time it has not change.

Does this help?

Edit: I think I have confused myself with the ordering so I updated the post above.

**Comment by jarupxx** [comment]
That's very helpful. I will fix some moved OOVPA to have missed Locking offset 0x00.

**Comment by RadWolfie** [comment]
You can also remove original OOVPA which was moved as well.

**Comment by PatrickvL** [comment]
May I hijack this discussion to say I've merged upstream master into my WIP branch, so if you're going to delete (edit: or move to an archive file) all old OOVPA that were moved to another version, then by all means, go ahead.

**Comment by jarupxx** [comment]
Are you sure that we can remove all old OOVPA? There is a possibility that it can be deleted at onece by regular expressions. I'll try it.

**Comment by RadWolfie** [comment]
Remove "move" _old_ OOVPAs only. We do not want to remove all old OOVPAs. And need to avoid "regular expressions" deletion process.

**Comment by RadWolfie** [comment]
LGTM

@jarupxx, do you want to do the removal of your old moved OOVPAs before I proceed merge into the branch?

**Comment by jarupxx** [comment]
I’d like to take it back about Remove old OOVPAs. Did not work regular expression I thought.

**Pull request merged**
